//go:build s390x

package adler32

import "golang.org/x/sys/cpu"

// adlerVX folds n whole 16-byte blocks of p into (s1, s2) using the z/Arch
// vector facility and returns the updated accumulators. Generated by go-asmgen
// (adler32_s390x_gen.go) into adler32_s390x.s. It performs no modular reduction
// (the caller keeps each call within nmax bytes so the 32-bit accumulators
// cannot overflow), and any 0..15-byte tail goes to updateChunk's scalar loop.
func adlerVX(s1, s2 uint32, p []byte, n int) (uint32, uint32)

const blockVX = 16

// hasVX reports whether the vector facility (z13+) is present; the vector
// instructions are unavailable on older models, so the kernel is only dispatched
// when true. The Force test also toggles it to exercise the scalar fallback.
var hasVX = cpu.S390X.HasVX

// simdBlockBytes returns the number of leading bytes of a len-l chunk the vector
// kernel folds (a whole multiple of 16); the rest goes to the scalar tail.
func simdBlockBytes(l int) int {
	if hasVX && l >= blockVX {
		return l &^ (blockVX - 1)
	}
	return 0
}

// chunkSIMD folds p (a whole multiple of 16, len <= nmax) into (s1, s2).
func chunkSIMD(s1, s2 uint32, p []byte) (uint32, uint32) {
	return adlerVX(s1, s2, p, len(p)/blockVX)
}
