// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64 && go1.27

#include "textflag.h"

TEXT ·adlerNEON(SB), NOSPLIT, $0-48
	MOVWU s1+0(FP), R0
	MOVWU s2+4(FP), R1
	MOVD p_base+8(FP), R2
	MOVD n+32(FP), R3
	MOVD $wlo<>(SB), R4
	VLD1 (R4), [V6.H8]
	MOVD $whi<>(SB), R4
	VLD1 (R4), [V7.H8]
	CBZ R3, done
loop:
	VLD1 (R2), [V3.B16]
	LSL $4, R0, R5
	ADD R5, R1, R1
	VUADDLV V3.B16, V4
	VMOV V4.S[0], R5
	ADD R5, R0, R0
	VUXTL V3.B8, V16.H8
	VUXTL2 V3.B16, V17.H8
	VUMULL V6.H4, V16.H4, V20.S4
	VUMULL2 V6.H8, V16.H8, V21.S4
	VUMULL V7.H4, V17.H4, V22.S4
	VUMULL2 V7.H8, V17.H8, V23.S4
	VADD V21.S4, V20.S4, V20.S4
	VADD V23.S4, V22.S4, V22.S4
	VADD V22.S4, V20.S4, V20.S4
	VUADDLV V20.S4, V24
	VMOV V24.D[0], R5
	ADD R5, R1, R1
	ADD $16, R2
	SUB $1, R3
	CBNZ R3, loop
done:
	MOVWU R0, R0
	MOVWU R1, R1
	MOVW R0, o1+40(FP)
	MOVW R1, o2+44(FP)
	RET

DATA wlo<>+0(SB)/1, $0x10
DATA wlo<>+1(SB)/1, $0x00
DATA wlo<>+2(SB)/1, $0x0f
DATA wlo<>+3(SB)/1, $0x00
DATA wlo<>+4(SB)/1, $0x0e
DATA wlo<>+5(SB)/1, $0x00
DATA wlo<>+6(SB)/1, $0x0d
DATA wlo<>+7(SB)/1, $0x00
DATA wlo<>+8(SB)/1, $0x0c
DATA wlo<>+9(SB)/1, $0x00
DATA wlo<>+10(SB)/1, $0x0b
DATA wlo<>+11(SB)/1, $0x00
DATA wlo<>+12(SB)/1, $0x0a
DATA wlo<>+13(SB)/1, $0x00
DATA wlo<>+14(SB)/1, $0x09
DATA wlo<>+15(SB)/1, $0x00
GLOBL wlo<>(SB), RODATA|NOPTR, $16

DATA whi<>+0(SB)/1, $0x08
DATA whi<>+1(SB)/1, $0x00
DATA whi<>+2(SB)/1, $0x07
DATA whi<>+3(SB)/1, $0x00
DATA whi<>+4(SB)/1, $0x06
DATA whi<>+5(SB)/1, $0x00
DATA whi<>+6(SB)/1, $0x05
DATA whi<>+7(SB)/1, $0x00
DATA whi<>+8(SB)/1, $0x04
DATA whi<>+9(SB)/1, $0x00
DATA whi<>+10(SB)/1, $0x03
DATA whi<>+11(SB)/1, $0x00
DATA whi<>+12(SB)/1, $0x02
DATA whi<>+13(SB)/1, $0x00
DATA whi<>+14(SB)/1, $0x01
DATA whi<>+15(SB)/1, $0x00
GLOBL whi<>(SB), RODATA|NOPTR, $16

