//go:build ppc64le

package adler32

import "golang.org/x/sys/cpu"

// adlerVSX folds n whole 16-byte blocks of p into (s1, s2) using the VSX/AltiVec
// vector unit and returns the updated accumulators. Generated by go-asmgen
// (adler32_ppc64le_gen.go) into adler32_ppc64le.s. It performs no modular
// reduction (the caller keeps each call within nmax bytes so the 32-bit
// accumulators cannot overflow), and any 0..15-byte tail goes to updateChunk's
// scalar loop. The kernel uses ISA-3.0 (POWER9) instructions (LXVB16X), which
// raise SIGILL on POWER8, so it runs only when hasVSX reports POWER9+.
func adlerVSX(s1, s2 uint32, p []byte, n int) (uint32, uint32)

const blockVSX = 16

// hasVSX is the dispatch flag. The generated kernel emits ISA-3.0 (POWER9)
// VSX instructions (e.g. LXVB16X) that are illegal on POWER8, so it is gated on
// POWER9 detection; on POWER8 simdBlockBytes returns 0 and the scalar tail in
// updateChunk folds every byte. It is a var (not a const) so the Force test can
// also drive the no-SIMD fallback on a POWER9+ host.
var hasVSX = cpu.PPC64.IsPOWER9

// simdBlockBytes returns the number of leading bytes of a len-l chunk the VSX
// kernel folds (a whole multiple of 16); the rest goes to the scalar tail.
func simdBlockBytes(l int) int {
	if hasVSX && l >= blockVSX {
		return l &^ (blockVSX - 1)
	}
	return 0
}

// chunkSIMD folds p (a whole multiple of 16, len <= nmax) into (s1, s2).
func chunkSIMD(s1, s2 uint32, p []byte) (uint32, uint32) {
	return adlerVSX(s1, s2, p, len(p)/blockVSX)
}
