//go:build amd64

package adler32

import "golang.org/x/sys/cpu"

// adlerSSE folds n whole 16-byte blocks of p into (s1, s2) and returns the
// updated accumulators; adlerAVX2 does the same over n whole 32-byte blocks.
// Both are generated by go-asmgen (adler32_gen.go) into adler32_amd64.s. They
// perform no modular reduction (the caller keeps each call within nmax bytes so
// the 32-bit accumulators cannot overflow).
func adlerSSE(s1, s2 uint32, p []byte, n int) (uint32, uint32)
func adlerAVX2(s1, s2 uint32, p []byte, n int) (uint32, uint32)

var hasAVX2 = cpu.X86.HasAVX2

// blockSSE and blockAVX2 are the kernels' block widths in bytes.
const (
	blockSSE  = 16
	blockAVX2 = 32
)

// simdBlockBytes returns the number of leading bytes of a len-l chunk that the
// widest available kernel will fold (a whole multiple of the block width).
func simdBlockBytes(l int) int {
	if hasAVX2 && l >= blockAVX2 {
		return l &^ (blockAVX2 - 1)
	}
	if l >= blockSSE {
		return l &^ (blockSSE - 1)
	}
	return 0
}

// chunkSIMD folds p (a whole multiple of the active block width, len <= nmax)
// into (s1, s2) with the widest available kernel.
func chunkSIMD(s1, s2 uint32, p []byte) (uint32, uint32) {
	if hasAVX2 && len(p) >= blockAVX2 {
		return adlerAVX2(s1, s2, p, len(p)/blockAVX2)
	}
	return adlerSSE(s1, s2, p, len(p)/blockSSE)
}
