//go:build riscv64

package adler32

import "golang.org/x/sys/cpu"

// adlerRVV folds the whole region p (len <= nmax) into (s1, s2) using the RISC-V
// vector extension and returns the updated accumulators. Generated by go-asmgen
// (adler32_riscv64_gen.go) into adler32_riscv64.s. The kernel is length-agnostic
// (VSETVLI per strip) and does no modular reduction.
func adlerRVV(s1, s2 uint32, p []byte, n int) (uint32, uint32)

// hasV reports whether the V (vector) extension is present; the V instructions
// trap on a hart without it, so the kernel is only dispatched when true.
var hasV = cpu.RISCV64.HasV

// simdBlockBytes folds the entire chunk in the vector loop when V is present
// (RVV handles any length, including a scalar-width tail, internally); without
// V the whole chunk goes to the scalar tail.
func simdBlockBytes(l int) int {
	if hasV {
		return l
	}
	return 0
}

// chunkSIMD folds p (len <= nmax) into (s1, s2) with the RVV kernel.
func chunkSIMD(s1, s2 uint32, p []byte) (uint32, uint32) {
	return adlerRVV(s1, s2, p, len(p))
}
