// Package adler32 is a drop-in fast path for the Adler-32 checksum,
// bit-for-bit identical to the standard library's hash/adler32. The bulk of the
// input is summed by a SIMD kernel generated by go-asmgen (amd64 SSE3/SSSE3,
// with an AVX2 path; arm64 NEON on Go 1.27+; riscv64 RVV uses its integer vector
// multiply; ppc64le VSX/AltiVec; s390x vector facility); architectures without a
// kernel (loong64, arm64 on stable Go, and others) fall back to a portable
// scalar loop that is identical to hash/adler32. The result always equals
// adler32.Checksum.
//
// Adler-32 over data d is s2<<16 | s1 where s1 = 1 + Σd[i] (mod 65521) and
// s2 = Σ running-s1 (mod 65521). The standard library is scalar (byte-by-byte;
// see golang/go#68188, the open proposal to add SIMD to the standard library).
// This package vectorises the inner sum: over a chunk of at most nmax bytes the
// 16-bit lane sums cannot overflow, so per chunk s1 += Σbytes and
// s2 += chunkLen*s1_before + Σ weight_i*byte_i with weights chunkLen..1 — the
// weighted sum being the SIMD core (PMADDUBSW on amd64).
package adler32

import "hash"

const (
	// mod is the largest prime less than 65536 (same as hash/adler32).
	mod = 65521
	// nmax is the largest n such that 255*n*(n+1)/2 + (n+1)*(mod-1) <= 2^32-1,
	// i.e. the longest run before the accumulators can overflow (same as
	// hash/adler32).
	nmax = 5552
)

// Checksum returns the Adler-32 checksum of data. It is bit-for-bit identical to
// hash/adler32.Checksum.
func Checksum(data []byte) uint32 { return uint32(update(1, data)) }

// digest mirrors hash/adler32's representation: the low 16 bits are s1 and the
// high 16 bits are s2.
type digest uint32

// update adds p to the running checksum d and returns the new digest. It is
// numerically identical to hash/adler32.update: chunk by nmax, sum, reduce mod
// 65521 at each chunk boundary. The per-chunk sum is delegated to the widest
// SIMD kernel for whole blocks, with an identical scalar tail.
func update(d digest, p []byte) digest {
	s1, s2 := uint32(d&0xffff), uint32(d>>16)
	for len(p) > 0 {
		var q []byte
		if len(p) > nmax {
			p, q = p[:nmax], p[nmax:]
		}
		s1, s2 = updateChunk(s1, s2, p)
		s1 %= mod
		s2 %= mod
		p = q
	}
	return digest(s2<<16 | s1)
}

// updateChunk folds one chunk (len <= nmax) into (s1, s2) without any modular
// reduction. It runs the SIMD kernel over whole blocks then a scalar tail over
// the remaining bytes. The scalar tail is identical to hash/adler32's inner
// loop, so the running totals match the standard library exactly.
func updateChunk(s1, s2 uint32, p []byte) (uint32, uint32) {
	if n := simdBlockBytes(len(p)); n > 0 {
		s1, s2 = chunkSIMD(s1, s2, p[:n])
		p = p[n:]
	}
	for _, x := range p {
		s1 += uint32(x)
		s2 += s1
	}
	return s1, s2
}

// New returns a new hash.Hash32 computing the Adler-32 checksum. Its Sum32 is
// bit-for-bit identical to hash/adler32.New().Sum32 for the same writes; the
// bulk of each Write is folded by the SIMD kernel.
func New() hash.Hash32 {
	d := new(adlerHash)
	d.Reset()
	return d
}

type adlerHash struct{ d digest }

func (h *adlerHash) Reset()         { h.d = 1 }
func (h *adlerHash) Size() int      { return 4 }
func (h *adlerHash) BlockSize() int { return 4 }
func (h *adlerHash) Sum32() uint32  { return uint32(h.d) }

func (h *adlerHash) Write(p []byte) (int, error) {
	h.d = update(h.d, p)
	return len(p), nil
}

func (h *adlerHash) Sum(in []byte) []byte {
	s := uint32(h.d)
	return append(in, byte(s>>24), byte(s>>16), byte(s>>8), byte(s))
}
