//go:build arm64 && go1.27

package adler32

// adlerNEON folds n whole 16-byte blocks of p into (s1, s2) and returns the
// updated accumulators. Generated by go-asmgen (adler32_arm64_gen.go) into
// adler32_arm64.s. It needs an integer NEON multiply for the weighted sum:
// Go's arm64 assembler only gained VMUL / VUMULL / VUMLAL upstream in Go 1.27
// (the polynomial VPMULL is unrelated), so this path is //go:build go1.27 and
// the stable build (adler32_generic.go) falls back to scalar on arm64. The
// kernel performs no modular reduction; the caller keeps each call within nmax.
func adlerNEON(s1, s2 uint32, p []byte, n int) (uint32, uint32)

const blockNEON = 16

// simdBlockBytes returns the number of leading bytes of a len-l chunk the NEON
// kernel folds (a whole multiple of 16).
func simdBlockBytes(l int) int {
	if l >= blockNEON {
		return l &^ (blockNEON - 1)
	}
	return 0
}

// chunkSIMD folds p (a whole multiple of 16, len <= nmax) into (s1, s2).
func chunkSIMD(s1, s2 uint32, p []byte) (uint32, uint32) {
	return adlerNEON(s1, s2, p, len(p)/blockNEON)
}
