//go:build ppc64le

package adler32

// adlerVSX folds n whole 16-byte blocks of p into (s1, s2) using the VSX/AltiVec
// vector unit and returns the updated accumulators. Generated by go-asmgen
// (adler32_ppc64le_gen.go) into adler32_ppc64le.s. It performs no modular
// reduction (the caller keeps each call within nmax bytes so the 32-bit
// accumulators cannot overflow), and any 0..15-byte tail goes to updateChunk's
// scalar loop. VSX is part of the ppc64le baseline (Power8+), so the kernel is
// always available; hasVSX exists only so the test can force the scalar path.
func adlerVSX(s1, s2 uint32, p []byte, n int) (uint32, uint32)

const blockVSX = 16

// hasVSX is the dispatch flag. VSX is baseline on ppc64le, so it is always true
// in production; the Force test toggles it to exercise the no-SIMD fallback
// (the scalar tail in updateChunk) on the same host.
var hasVSX = true

// simdBlockBytes returns the number of leading bytes of a len-l chunk the VSX
// kernel folds (a whole multiple of 16); the rest goes to the scalar tail.
func simdBlockBytes(l int) int {
	if hasVSX && l >= blockVSX {
		return l &^ (blockVSX - 1)
	}
	return 0
}

// chunkSIMD folds p (a whole multiple of 16, len <= nmax) into (s1, s2).
func chunkSIMD(s1, s2 uint32, p []byte) (uint32, uint32) {
	return adlerVSX(s1, s2, p, len(p)/blockVSX)
}
